<?
include 'conectar.php';
if (isset($_POST['conte'])){
    $consulta2="insert into nota(id_n,nombre,fecha,periodico,user,contenido)
values(id_n,'".$_POST['titulo']."','".$_POST['fecha']."','".$_POST['selec']."','".$_SESSION['id_user']."','".$_POST['conte']."')";
                mysql_query($consulta2) or die (mysql_error());
//echo "Nota Agregada!!<br>";
  //  echo "del periodico".$_POST['titulo'];
echo '<script> alert("agregado"); </script>';
}
?>
<!DOCTYPE html>
<?
session_start();
?>
<html>
<head>
    <title> UPN-Repositorio    </title>
    <link rel="stylesheet" type="text/css" href="sty.css" />
    <meta charset="utf-8">
   <!--meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"> 
    <meta name="description" content="An Icon Font Generated By IcoMoon.io"-->
     
        <script src="jquery.min.js"></script>
<script src="slides.min.jquery.js"></script>
		<script>
            $(function(){
                $("#slideshow").slides({
        effect: 'slide,' ,
                    play: 5000,
                   effect: 'fade' ;
                    
      });
            });
        </script>
    <script type="text/javascript">
			$(document).ready(function() {
				$("#biblio").click(function(event) {
					$("#contenido").load("consul.php");
                });
                $("#c").click(function(event) {
					$("#contenido").load("contacto.html");         
				   });
                  $("#subir").click(function(event) {
					$("#contenido").load("form.php");         
				   });
                $("#login").click(function(event) {
					$("#contenido").load("index2.php");         
				   });
			 });			
		</script>
    </head>
    <body>
        <div class="contenedor">
            <header>
			<div id="subheader">
				<div id="logotipo"><p><a href="index.php"><img src="logoupn.png" width="100" height="100"/></a></p></div>
                <div id="buscador" class="texto"> <form id="crd" method="post" action="buscar.php">
                <input name="buscar" id="buscar" required><input type="submit" value="buscar">
                </form>
                
                </div>
                <ul class="nav">
				<li><a href="index.php"> Inicio </a></li>
				<li><a href=""> Periodicos </a>
					<ul>
                        <li><a name="b" id="b" style=cursor:pointer;> la jornada </a></li>
						<li><a href="#"> el sur </a></li>
						<li><a href="#"> la jornada guerrero </a></li>
                        <li><a href="#"> diario 21 </a></li>
                      
					</ul>
				</li>
				<li><a name="biblio" id="biblio" style=cursor:pointer;> Biblioteca </a>
					<!--ul>
				        <li><a name="b1" id="b1" style=cursor:pointer;> la jornada </a></li>
						<li><a name="b2" id="b1" style=cursor:pointer;> el sur </a></li>
						<li><a name="b3" id="b1" style=cursor:pointer;> la jornada guerrero </a></li>
                        <li><a name="b4" id="b1" style=cursor:pointer;> diario 21 </a></li>                        
					</ul-->
				</li>
                <li><a id="c" name="c" style=cursor:pointer;> Contactanos </a></li>
                    
                    <? 
                    if(isset($_SESSION['id_user'])){
                    echo "<li><a href=perfil.php style=cursor:pointer;>Perfil</a></li>
                        <li><a id=subir name=subir style=cursor:pointer;>Subir</a></li>
                        <li><a href=salir.php style=cursor:pointer;> Salir </a></li>";
                        }
                    else{
                    echo "<li><a style=cursor:pointer; id=login >Ingresar</a></li>";
                        }
                    ?>
                    
			</ul>
			</div>
		</header>
            <section id="wrap">

		<section id="main">

			<section id="contenido" >
				
                <?
                if(isset($_GET['variable'])){
                //echo $_POST['variable'];
                $s1 = "select * from nota where periodico='".$_GET['variable']."'";
                //echo $s1;
                    echo "Notas:<br>";
                $s2 = mysql_query($s1) or die(mysql_error());
                while($s3=mysql_fetch_assoc($s2)){
                        echo " <a href=consul311.php?var2=".$s3['id_n']." target=_blanck>".$s3['nombre']."</a><br>";
                    
                }
                }
                ?>
                
			</section>

			<section id="contenidoooo" >
				<article>
				
				</article>

			</section>

			<aside>
				<section class="widget">
					<h3>Articulos Recientes</h3>
					<ul>
						<?
                        $max="select * from nota order by id_n desc limit 5";
                        $max2=mysql_query($max) or die (mysql_error());
                        while ($max3=mysql_fetch_assoc($max2)){
                            echo "<li><a href=consul311.php?var2=".$max3['id_n']." target=_blank>".$max3['nombre']."</a></li>" ;
                        }                      
                        ?>
					</ul>
				</section>

			</aside>

		</section>

		<footer>
            <section id="acerca-de">
		Todos los derechos reservados a grupo de desarroladores.
            <p> Slides efectos Slides.jquery by Nathan Searles, http://nathansearles.com
* Version: 1.2</p>
            </section>

		</footer>

		<div id="copyright"><p> © 2016 UPEG-Victor, Cristian, Ma. de la Luz, Karina, Abraham </p></div>

	</section>

            </div>
    </body>
</html>
